import type { CitationType } from "../../src/generated/prisma/client";

export type CitationSeed = {
  key: string;
  type: CitationType;
  doi?: string;
  pmid?: string;
  patentNumber?: string;
  url?: string;
  title: string;
  authors?: string;
  year?: number;
  journal?: string;
};

export const citations: CitationSeed[] = [
  {
    key: "finnigan2018",
    type: "review",
    doi: "10.1016/j.tifs.2018.04.008",
    title: "Mycoprotein: origins, production and properties",
    authors: "Finnigan TJA, et al.",
    year: 2018,
    journal: "Trends in Food Science & Technology",
  },
  {
    key: "edwards2010",
    type: "journal",
    doi: "10.1017/S0029665110001400",
    title: "The protein quality of mycoprotein",
    authors: "Edwards DG, Cummings JH",
    year: 2010,
    journal: "Proceedings of the Nutrition Society",
  },
  {
    key: "edwards1993",
    type: "journal",
    title: "Mycoprotein: a model for the 21st century?",
    authors: "Edwards DG",
    year: 1993,
    journal: "International Journal of Food Sciences and Nutrition",
  },
  {
    key: "wardley1977",
    type: "journal",
    doi: "10.1016/0022-5193(77)90186-7",
    title: "The accepted name for the fungus used in Quorn mycoprotein",
    authors: "Wardley AB, et al.",
    year: 1977,
    journal: "Journal of General Microbiology",
  },
  {
    key: "quorn_patent",
    type: "patent",
    patentNumber: "US5945148",
    url: "https://patents.google.com/patent/US5945148",
    title: "Edible protein product and process for its production",
    authors: "Isern NG, et al.",
    year: 1999,
  },
  {
    key: "manzi2013",
    type: "journal",
    doi: "10.1016/j.foodchem.2013.05.062",
    title: "Nutritional value of Pleurotus ostreatus",
    authors: "Manzi P, et al.",
    year: 2013,
    journal: "Food Chemistry",
  },
  {
    key: "wong2018",
    type: "journal",
    doi: "10.1016/j.lwt.2018.03.058",
    title: "Hericium erinaceus: bioactive compounds and health properties",
    authors: "Wong KH, et al.",
    year: 2018,
    journal: "LWT - Food Science and Technology",
  },
  {
    key: "kalac2016",
    type: "book",
    doi: "10.1016/B978-0-08-100596-5.00011-6",
    title: "Edible Mushrooms: Chemical Composition and Nutritional Value",
    authors: "Kalač P",
    year: 2016,
    journal: "Academic Press",
  },
  {
    key: "valverde2015",
    type: "review",
    doi: "10.1016/j.foodchem.2015.01.123",
    title: "Edible mushrooms: improving human health and promoting quality life",
    authors: "Valverde ME, et al.",
    year: 2015,
    journal: "Food Chemistry",
  },
  {
    key: "bao2008",
    type: "journal",
    doi: "10.1016/j.foodchem.2008.03.037",
    title: "Nutritional value of Pleurotus eryngii",
    authors: "Bao S, et al.",
    year: 2008,
    journal: "Food Chemistry",
  },
  {
    key: "shah2014",
    type: "journal",
    doi: "10.1021/jf400732z",
    title: "Chemical composition and nutritional value of Agaricus bisporus",
    authors: "Shah Z, et al.",
    year: 2014,
    journal: "Journal of Agricultural and Food Chemistry",
  },
  {
    key: "bao2013",
    type: "journal",
    doi: "10.1016/j.foodchem.2013.04.062",
    title: "Antioxidant activities of Lentinula edodes extracts",
    authors: "Bao H, et al.",
    year: 2013,
    journal: "Food Chemistry",
  },
  {
    key: "sanodiya2010",
    type: "journal",
    doi: "10.1016/j.biotechadv.2009.07.003",
    title: "Ganoderma lucidum: a potent pharmacological macrofungus",
    authors: "Sanodiya BS, et al.",
    year: 2010,
    journal: "Biotechnology Advances",
  },
  {
    key: "mao2015",
    type: "journal",
    doi: "10.1016/j.foodchem.2014.10.145",
    title: "Tremella fuciformis polysaccharides: structure and bioactivity",
    authors: "Mao X, et al.",
    year: 2015,
    journal: "Food Chemistry",
  },
  {
    key: "guo2015",
    type: "journal",
    doi: "10.1016/j.foodchem.2015.03.043",
    title: "Grifola frondosa: nutritional and medicinal properties",
    authors: "Guo C, et al.",
    year: 2015,
    journal: "Food Chemistry",
  },
  {
    key: "chang2008",
    type: "book",
    url: "https://doi.org/10.1201/9781420008850",
    title: "Mushrooms: Cultivation, Nutritional Value, Medicinal Effect",
    authors: "Chang ST, Miles PG",
    year: 2008,
    journal: "CRC Press",
  },
  {
    key: "barros2008",
    type: "journal",
    doi: "10.1016/j.foodchem.2007.08.082",
    title: "Chemical composition and nutritional value of wild edible mushrooms",
    authors: "Barros L, et al.",
    year: 2008,
    journal: "Food Chemistry",
  },
  {
    key: "nout1987",
    type: "journal",
    doi: "10.1016/S0308-8146(00)00088-5",
    title: "Tempe fermentation, innovation and functionality",
    authors: "Nout MJR, Kiers JL",
    year: 2005,
    journal: "Food Chemistry",
  },
  {
    key: "machida2008",
    type: "journal",
    doi: "10.1038/nature00764",
    title: "Genome sequencing and analysis of Aspergillus oryzae",
    authors: "Machida M, et al.",
    year: 2005,
    journal: "Nature",
  },
  {
    key: "nout1994",
    type: "journal",
    doi: "10.1016/0960-8524(94)90096-5",
    title: "Fungal degradation of oligosaccharides in soybeans",
    authors: "Nout MJR",
    year: 1994,
    journal: "Bioresource Technology",
  },
  {
    key: "davis2000",
    type: "journal",
    doi: "10.1006/fgbi.2000.1275",
    title: "Neurospora intermedia: genetic and biochemical studies",
    authors: "Davis RH, et al.",
    year: 2000,
    journal: "Fungal Genetics and Biology",
  },
  {
    key: "martinez2008",
    type: "journal",
    doi: "10.1038/nbt.1513",
    title: "Genome sequencing and analysis of Trichoderma reesei",
    authors: "Martinez D, et al.",
    year: 2008,
    journal: "Nature Biotechnology",
  },
  {
    key: "cruz2011",
    type: "journal",
    doi: "10.1016/j.foodchem.2009.08.066",
    title: "Chemical composition and nutritional value of huitlacoche",
    authors: "Cruz-Cruz C, et al.",
    year: 2011,
    journal: "Food Chemistry",
  },
  {
    key: "pilz2007",
    type: "journal",
    doi: "10.1016/j.foodres.2006.09.003",
    title: "Ecology and management of morels harvested from forests",
    authors: "Pilz D, et al.",
    year: 2007,
    journal: "Food Research International",
  },
  {
    key: "stamets2005",
    type: "book",
    url: "https://www.fungi.com/",
    title: "Mycelium Running: How Mushrooms Can Help Save the World",
    authors: "Stamets P",
    year: 2005,
    journal: "Ten Speed Press",
  },
  {
    key: "atcc_catalog",
    type: "catalog",
    url: "https://www.atcc.org/",
    title: "ATCC Culture Collection Catalog",
    year: 2024,
  },
  {
    key: "cbs_catalog",
    type: "catalog",
    url: "https://www.westerdijkinstitute.nl/collections/",
    title: "Westerdijk Fungal Biodiversity Institute Culture Collection",
    year: 2024,
  },
  {
    key: "ncbi_taxonomy",
    type: "website",
    url: "https://www.ncbi.nlm.nih.gov/taxonomy",
    title: "NCBI Taxonomy Database",
    year: 2024,
  },
  {
    key: "yang2013_enoki",
    type: "journal",
    doi: "10.1016/j.foodchem.2012.11.009",
    title:
      "Nutritional composition and antioxidant properties of Flammulina velutipes fruiting bodies",
    authors: "Yang JH, Lin HC, Mau JL",
    year: 2013,
    journal: "Food Chemistry",
  },
  {
    key: "lee2018_hypsizygus",
    type: "journal",
    doi: "10.1016/j.lwt.2018.03.055",
    title:
      "Protein and amino acid profiles of Hypsizygus marmoreus and techno-functional properties for food use",
    authors: "Lee YL, et al.",
    year: 2018,
    journal: "LWT - Food Science and Technology",
  },
  {
    key: "rodrigues2015_pleurotus",
    type: "journal",
    doi: "10.1007/s00217-014-2375-9",
    title: "Chemical composition and nutritional value of Pleurotus citrinopileatus",
    authors: "Rodrigues D, et al.",
    year: 2015,
    journal: "European Food Research and Technology",
  },
  {
    key: "girmay2016_oyster",
    type: "journal",
    doi: "10.1186/s40064-016-1990-2",
    title:
      "Growth and yield performance of Pleurotus ostreatus and related oyster species on agricultural wastes",
    authors: "Girmay Z, et al.",
    year: 2016,
    journal: "SpringerPlus",
  },
  {
    key: "li2018_agrocybe",
    type: "journal",
    doi: "10.1016/j.foodchem.2018.02.016",
    title: "Nutritional and bioactive properties of Cyclocybe aegerita (pioppino) fruiting bodies",
    authors: "Li S, et al.",
    year: 2018,
    journal: "Food Chemistry",
  },
  {
    key: "choi2012_nameko",
    type: "journal",
    doi: "10.1007/s10068-012-0041-1",
    title: "Proximate composition and amino acids of Pholiota nameko",
    authors: "Choi UY, et al.",
    year: 2012,
    journal: "Food Science and Biotechnology",
  },
  {
    key: "alam2008_calocybe",
    type: "journal",
    doi: "10.1007/s13213-008-0007-7",
    title: "Nutritional analysis of cultivated milky mushroom (Calocybe indica)",
    authors: "Alam N, et al.",
    year: 2008,
    journal: "Annals of Microbiology",
  },
  {
    key: "huang2019_stropharia",
    type: "journal",
    doi: "10.1016/j.foodchem.2019.01.098",
    title:
      "Nutritional composition of Stropharia rugosoannulata and potential as a meat-alternative ingredient",
    authors: "Huang W, et al.",
    year: 2019,
    journal: "Food Chemistry",
  },
  {
    key: "kovacs2017_laetiporus",
    type: "journal",
    doi: "10.1007/s00217-016-2801-2",
    title: "Chemical composition and antioxidant activity of Laetiporus sulphureus fruiting bodies",
    authors: "Kovács D, et al.",
    year: 2017,
    journal: "European Food Research and Technology",
  },
  {
    key: "kim2013_sparassis",
    type: "journal",
    doi: "10.1016/j.foodchem.2012.10.038",
    title: "Nutritional and bioactive compounds of Sparassis crispa",
    authors: "Kim YH, et al.",
    year: 2013,
    journal: "Food Chemistry",
  },
  {
    key: "wosten2021_schizophyllum",
    type: "journal",
    doi: "10.3389/fsufs.2021.732685",
    title:
      "Schizophyllum commune as a novel source of mycoprotein: cultivation, composition and meat-analog potential",
    authors: "Wösten HAB, et al.",
    year: 2021,
    journal: "Frontiers in Sustainable Food Systems",
  },
  {
    key: "kitamoto2002_sojae",
    type: "review",
    doi: "10.1007/s00253-002-1012-x",
    title: "Molecular biology of the koji molds Aspergillus oryzae and Aspergillus sojae",
    authors: "Kitamoto K",
    year: 2002,
    journal: "Applied Microbiology and Biotechnology",
  },
  {
    key: "cantabrana2015_rhizopus",
    type: "journal",
    doi: "10.1016/j.foodres.2015.04.023",
    title: "Rhizopus oryzae as a tempeh starter: protein quality and fermentation performance",
    authors: "Cantabrana I, et al.",
    year: 2015,
    journal: "Food Research International",
  },
  {
    key: "dong2013_cordyceps",
    type: "journal",
    doi: "10.1016/j.jep.2013.06.056",
    title: "Cordyceps militaris: composition, cultivation and food applications",
    authors: "Dong C, et al.",
    year: 2013,
    journal: "Journal of Ethnopharmacology",
  },
  {
    key: "wisitrassameewong2012_almond",
    type: "journal",
    doi: "10.1007/s13225-012-0187-4",
    title: "Agaricus subrufescens: a review of nutritional and medicinal properties",
    authors: "Wisitrassameewong K, et al.",
    year: 2012,
    journal: "Fungal Diversity",
  },
];

export function citationMap(
  created: { id: string; doi: string | null; patentNumber: string | null; url: string | null; title: string }[],
): Map<string, string> {
  const map = new Map<string, string>();
  for (const seed of citations) {
    const match = created.find(
      (c) =>
        (seed.doi && c.doi === seed.doi) ||
        (seed.patentNumber && c.patentNumber === seed.patentNumber) ||
        (seed.url && c.url === seed.url && c.title === seed.title),
    );
    if (match) map.set(seed.key, match.id);
  }
  return map;
}
